# Generated by Django 4.2.7 on 2023-12-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about_product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='popular',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_2',
        ),
    ]
