# Generated by Django 4.2.7 on 2023-12-26 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
