# Generated by Django 4.2.7 on 2023-12-23 17:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about_descriptions_2_about_image_2_about_title_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='logo',
            new_name='logo_dark',
        ),
        migrations.AddField(
            model_name='settings',
            name='logo_light',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
