# Generated by Django 4.2.7 on 2023-12-23 17:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_logo_settings_logo_dark_settings_logo_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo_dark',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип для темной темы'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo_light',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип для светлой темы'),
        ),
    ]
